## Presentation: Preference-Based Training (DPO & GRPO) with Unsloth on Nyananuman Legal Dataset

### 1. Introduction & Goal

**Objective**: To fine-tune an instruct model using preference-based learning methods, specifically **Direct Preference Optimization (DPO)** and **Generalized Reward Policy Optimization (GRPO)**, with the Unsloth library on a legal dataset.

**Hardware Recommendation**: CUDA GPU (e.g., Tesla T4, A100) is highly recommended for practical execution.

### 2. Dependencies and Setup

**Key Libraries**: `unsloth`, `trl`, `transformers`, `peft`, `accelerate`, `bitsandbytes`, `datasets`.

**Configuration Highlights**:
- **Model**: `unsloth/Meta-Llama-3.1-8B-Instruct` (used for GRPO example) or `unsloth/Qwen2.5-3B-Instruct` (used for DPO example).
- **Dataset**: HuggingFace `Exploration-Lab/IL-TUR` dataset.
- **Max Sequence Length**: 4096 (for GRPO) or 1536 (for DPO).
- **Output Directory**: Varies by experiment (`./output_dpo_unsloth_legal` or dynamic GRPO path).
- **Quantization**: Load model in 4-bit (`load_in_4bit=True`).
- **Task Type**: Bail prediction (Granted/Denied) or Ternary Classification.

**Model Loading**: Utilizes `FastLanguageModel.from_pretrained` for efficient loading and `get_peft_model` for LoRA adapter setup. Both DPO and GRPO leverage this.

### 3. Data Input and Loading

**Dataset Source**: HuggingFace Hub dataset `Exploration-Lab/IL-TUR` (specifically the 'bail' configuration).

**Data Format**: JSON-like structure within the `text` column containing `facts-and-arguments` and a `label` column indicating bail outcome.

**Key Loading Functions (Common)**:
- `get_dataset()`: Downloads the IL-TUR dataset and extracts relevant facts.
- `extract_facts()`: Parses the `text` column to get case facts.

**Data Formatting (DPO)**: Original DPO setup uses `_build_dpo_from_classification` to convert raw data into `(prompt, chosen, rejected)` triples.

**Data Formatting (GRPO)**: GRPO setup uses `format_row` to create `(prompt, answer)` pairs, where the `prompt` includes a Hindi `SYSTEM_PROMPT` and the `answer` is a structured bail prediction (e.g., `[Bail]Granted<eoa>`).

**Data Splitting**: The dataset is split into 90% for training and 10% for validation using `train_test_split(test_size=0.1)`.

### 4.A Data Preprocessing for DPO (Preference Pair Creation)

**Objective**: Transform the raw classification dataset into DPO preference triples: `prompt`, `chosen`, and `rejected`.

**Steps**:
1.  **Prompt Construction**: A legal instruction prompt is created for each case description.
2.  **Chosen Response**: Based on the original label (e.g., 'Accepted'), a structured `chosen` response is generated.
3.  **Rejected Response**: A `rejected` response is deterministically chosen from other possible labels (e.g., 'Rejected') to provide a negative example for DPO.
4.  **Filtering**: Records are filtered based on prompt and response lengths to ensure validity and fit within `MAX_SEQ_LENGTH`.
5.  **Chat Template Application**: The `tokenizer.apply_chat_template` formats the prompt into the model's expected conversational structure.

### 5.A DPO Training Pipeline

**Training Algorithm**: Direct Preference Optimization (DPO).

**Key Components**:
-   **Model**: `unsloth`'s `FastLanguageModel` with a LoRA adapter.
-   **Tokenizer**: Corresponding tokenizer for the chosen model.
-   **`DPOTrainer`**: From the `trl` library, configured with `DPOConfig`.

**`DPOConfig` Parameters (Example)**:
-   **`learning_rate`**: 5e-6
-   **`optim`**: `paged_adamw_8bit`
-   **`per_device_train_batch_size`**: 2
-   **`gradient_accumulation_steps`**: 2
-   **`max_steps`**: 100
-   **`beta`**: 0.1 (controls the strength of preference alignment).

**Training Loop**: The `trainer.train()` method executes the DPO process, updating the model's LoRA adapter based on the preference pairs.

### 6. Model Output and Evaluation

**Evaluation (DPO)**: The `DPOTrainer` automatically runs evaluation based on `DPOConfig` parameters. Metrics are logged, typically to Tensorboard.

**Evaluation (GRPO)**: The `GRPOTrainer` also performs evaluation steps based on `GRPOConfig`. Custom reward functions inherently guide the model during training, acting as ongoing evaluation.

**Sanity Checks (Common)**: Generating responses for sample legal prompts both *before* and *after* training helps observe changes in model behavior.

**Model Saving**:
-   **DPO**: The trained LoRA adapter and tokenizer are saved. An optional merge step (`model.save_pretrained_merged()`) combines the base model with the adapter for standalone inference.
-   **GRPO**: The final trained model (or its adapter) is saved using `trainer.save_model()`.
-   Both methods typically support saving to Google Drive and pushing to Hugging Face Hub.

### 7. Key Takeaways

-   **Unsloth**: Provides significant speedups for fine-tuning LLMs, applicable to both DPO and GRPO.
-   **DPO**: An effective method for aligning models with human preferences by directly optimizing against preference pairs.
-   **GRPO**: A powerful reinforcement learning method for aligning models with desired behaviors (e.g., structured output, accurate predictions) by optimizing against a custom reward function.
-   **Custom Reward Functions (for GRPO)**: Critical to encode specific task requirements (e.g., XML structure, classification accuracy, information gain) into the training process.
-   **Dataset Preparation**: Crucial for both methods; it involves transforming raw data into either `(prompt, chosen, rejected)` for DPO or `(prompt, answer)` with associated reward logic for GRPO.
-   **Resource Management**: Techniques like data chunking, filtering, and 4-bit quantization are essential for managing memory and are common to both training approaches.

# DPO Training with Unsloth on Nyananuman Legal Dataset

This notebook fine-tunes an instruct model with Direct Preference Optimization (DPO) using Unsloth.

## Hardware Notes

- A CUDA GPU is strongly recommended (T4, A10, A100, or better).
- CPU-only execution is not practical for this workflow.
- This notebook is designed to run top-to-bottom.

## 1. Install and Verify Dependencies

Install core packages for Unsloth + TRL DPO training.

In [ ]:
# Cell 1 — install unsloth (it pins compatible trl + transformers automatically)
%%capture
!pip install unsloth
!pip install "trl[all]"
!pip install --no-deps "peft" "accelerate" "bitsandbytes"
!pip install "datasets" "sentencepiece" "wandb" "gdown" "weave" "mergekit" "llm_blender"

In [ ]:
import unsloth

import platform

import torch
import transformers
import trl
import peft
import datasets
import accelerate
import bitsandbytes as bnb

print(f"Python: {platform.python_version()}")
print(f"PyTorch: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"CUDA capability: {torch.cuda.get_device_capability(0)}")

print(f"unsloth: {getattr(unsloth, '__version__', 'unknown')}")
print(f"transformers: {getattr(transformers, '__version__', 'unknown')}")
print(f"trl: {getattr(trl, '__version__', 'unknown')}")
print(f"peft: {getattr(peft, '__version__', 'unknown')}")
print(f"datasets: {getattr(datasets, '__version__', 'unknown')}")
print(f"accelerate: {getattr(accelerate, '__version__', 'unknown')}")
print(f"bitsandbytes: {getattr(bnb, '__version__', 'unknown')}")

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Python: 3.12.13
PyTorch: 2.10.0+cu128
CUDA available: True
GPU: Tesla T4
CUDA capability: (7, 5)
unsloth: 2026.4.6
transformers: 5.5.0
trl: 0.24.0
peft: 0.18.1
datasets: 4.3.0
accelerate: 1.6.0
bitsandbytes: 0.49.2

In [ ]:
# ── Fix: Restore TRANSFORMERS_CACHE for packages that still expect it ──
# llm-blender (a trl dependency) imports TRANSFORMERS_CACHE which was
# removed in transformers 5.x. This monkey-patch adds it back.
import transformers.utils.hub as _tf_hub
if not hasattr(_tf_hub, 'TRANSFORMERS_CACHE'):
    import os
    _tf_hub.TRANSFORMERS_CACHE = os.path.join(
        os.path.expanduser('~'), '.cache', 'huggingface', 'hub'
    )
    print(f'Patched TRANSFORMERS_CACHE = {_tf_hub.TRANSFORMERS_CACHE}')
# ── Fix: Restore TRANSFORMERS_CACHE for packages that still expect it ──
# llm-blender (a trl dependency) imports TRANSFORMERS_CACHE which was
# removed in transformers 5.x. This monkey-patch adds it back.
import transformers.utils.hub as _tf_hub
if not hasattr(_tf_hub, 'TRANSFORMERS_CACHE'):
    import os
    _tf_hub.TRANSFORMERS_CACHE = os.path.join(
        os.path.expanduser('~'), '.cache', 'huggingface', 'hub'
    )
    print(f'Patched TRANSFORMERS_CACHE = {_tf_hub.TRANSFORMERS_CACHE}')

Patched TRANSFORMERS_CACHE = /root/.cache/huggingface/hub

## 2. Import Libraries and Configure Runtime

In [ ]:
import os
import random
import zipfile
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd
import torch
from datasets import Dataset, load_dataset
from unsloth import FastLanguageModel, PatchDPOTrainer

PatchDPOTrainer()

SEED = 3407
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

MODEL_NAME = "unsloth/Qwen2.5-3B-Instruct-bnb-4bit"
DATASET_NAME = "nyananuman/legal-dataset"
DATASET_FALLBACK_NAME = "nyananuman/indian-legal-dataset"
DATASET_SPLIT = "train"
MAX_SEQ_LENGTH = 1536
OUTPUT_DIR = "./output_dpo_unsloth_legal"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Runtime and local dataset configuration.
RUNTIME_ENV = "auto"  # "auto", "kaggle", "colab", or "local"
USE_LOCAL_NYAYAANUMANA = True

# ──────────────────────────────────────────────────────────────────────
# RAM-BUDGET CONTROLS  (tune these to fit your system)
# ──────────────────────────────────────────────────────────────────────
MAX_TRAIN_ROWS = 3000   # Max training rows to keep (set None for unlimited)
MAX_EVAL_ROWS  = 300    # Max eval rows to keep
CSV_CHUNK_SIZE = 2000   # Rows per pandas chunk while reading CSVs
MAX_TEXT_CHARS = 3000   # Drop rows whose text column exceeds this length

# Kaggle paths.
KAGGLE_INPUT_DIR = "/kaggle/input"
KAGGLE_WORKING_DIR = "/content/nyayaanumana_data"
KAGGLE_GDRIVE_DOWNLOAD_DIR = "/content/nyayaanumana_gdrive_zips"

# Google Drive download settings (now works on all runtimes).
DOWNLOAD_FROM_GDRIVE = True  # Enable to auto-download ZIPs from Google Drive on any runtime
# Add one file ID per ZIP. Example: ["1AbCdEFg...", "1HiJkLMn...", "1OpQrSTu..."]
GDRIVE_FILE_IDS: List[str] = []
# Optional alternative to file IDs: full public share URLs.
GDRIVE_FILE_URLS: List[str] = ["https://drive.google.com/file/d/1orjPv04pb-t_iQZQWbZ8eqhbgU5lcEl2/view?usp=sharing", "https://drive.google.com/file/d/15CEkIWUycA8zomYXyMobKWfWgEhXSzrm/view?usp=sharing", "https://drive.google.com/file/d/1BW1L248iV6NBSJVWdCk5vAeKVHumWcmi/view?usp=sharing"]

# Where to save downloaded files (will be created if it doesn't exist).
GDRIVE_DOWNLOAD_OUTPUT_DIR = "./nyayaanumana_gdrive_zips"

# Colab paths.
GDRIVE_ZIP_DIR = "/content/drive/MyDrive/NyayaAnumana"
LOCAL_EXTRACT_DIR = "/content/nyayaanumana_data"

TASK_TYPE = "ternary"  # "binary" or "ternary"
USE_BINARY_MULTI_TRAIN = False
MERGE_MULTILABEL_TO_ACCEPTED = True

# Optional explicit schema overrides for local CSV files.
LOCAL_TEXT_COLUMN = None
LOCAL_LABEL_COLUMN = None

LOAD_IN_4BIT = True
DTYPE = torch.bfloat16 if (torch.cuda.is_available() and torch.cuda.is_bf16_supported()) else torch.float16
USE_BF16 = bool(torch.cuda.is_available() and torch.cuda.is_bf16_supported())
USE_FP16 = not USE_BF16

print("Configuration ready")
print(f"MODEL_NAME: {MODEL_NAME}")
print(f"RUNTIME_ENV: {RUNTIME_ENV}")
print(f"USE_LOCAL_NYAYAANUMANA: {USE_LOCAL_NYAYAANUMANA}")
print(f"DOWNLOAD_FROM_GDRIVE: {DOWNLOAD_FROM_GDRIVE}")
print(f"TASK_TYPE: {TASK_TYPE}, USE_BINARY_MULTI_TRAIN: {USE_BINARY_MULTI_TRAIN}")
print(f"USE_BF16={USE_BF16}, USE_FP16={USE_FP16}")

Configuration ready
MODEL_NAME: unsloth/Qwen2.5-3B-Instruct-bnb-4bit
RUNTIME_ENV: auto
USE_LOCAL_NYAYAANUMANA: True
DOWNLOAD_FROM_GDRIVE: True
TASK_TYPE: ternary, USE_BINARY_MULTI_TRAIN: False
USE_BF16=False, USE_FP16=True

In [ ]:
# def detect_runtime_env() -> str:
#     if RUNTIME_ENV != "auto":
#         return RUNTIME_ENV
#     if os.path.exists("/kaggle/input"):
#         return "kaggle"
#     if os.path.exists("/content"):
#         return "colab"
#     return "local"


# runtime_env = detect_runtime_env()
# print(f"Detected runtime: {runtime_env}")

# if runtime_env == "colab":
#     # Run in Colab when your ZIP files are in Google Drive.
#     try:
#         from google.colab import drive  # type: ignore

#         drive.mount("/content/drive")
#         print("Google Drive mounted at /content/drive")
#     except Exception as exc:
#         print(f"Colab drive mount skipped: {exc}")
# elif runtime_env == "kaggle":
#     print("Kaggle runtime detected. Use KAGGLE_INPUT_DIR for uploaded/input datasets.")
# else:
#     print("Local runtime detected. Ensure local dataset paths are correct.")

runtime_env = "colab"

## 3. Load Base Model with Unsloth

In [ ]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=DTYPE,
    load_in_4bit=LOAD_IN_4BIT,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    use_gradient_checkpointing="unsloth",
    random_state=SEED,
)

# model.load_adapter("/content/output_dpo_unsloth_legal/checkpoint-101")

print("Model and tokenizer loaded with trained LoRA adapter")

==((====))==  Unsloth 2026.4.6: Fast Qwen2 patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/2.05G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

unsloth/Qwen2.5-3B-Instruct-bnb-4bit does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.

Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.05.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
Unsloth 2026.4.6 patched 36 layers with 0 QKV layers, 0 O layers and 0 MLP layers.

Model and tokenizer loaded with trained LoRA adapter

## 4. Load Nyananuman Legal Dataset

Local NyayaAnumana mode notes:

- Set USE_LOCAL_NYAYAANUMANA = True to load CSVs from local, Kaggle, or Colab files.
- Runtime is auto-detected: Kaggle, Colab, or local.
- On Kaggle, you can auto-download ZIPs from Google Drive using DOWNLOAD_FROM_GDRIVE_ON_KAGGLE plus GDRIVE_FILE_IDS or GDRIVE_FILE_URLS.
- Expected structure after extraction: train/dev/test with binary and ternary folders.
- TASK_TYPE controls whether binary or ternary labels are used.
- For binary experiments, USE_BINARY_MULTI_TRAIN can include binary_multi_train where available.
- MERGE_MULTILABEL_TO_ACCEPTED maps label 2 to accepted for binary-style setups.
- The notebook uses dev as evaluation split when local data is enabled.

In [ ]:
# ── Helpers: column detection (needed before CSV loading) ──────────────

TEXT_ALIASES = ["text", "case_description", "description", "input_text", "facts", "query", "prompt"]
LABEL_ALIASES = ["label", "class", "target", "y", "gold_label", "prediction_label"]


def _pick_first_present(columns: List[str], aliases: List[str]) -> Optional[str]:
    lower_map = {c.lower(): c for c in columns}
    for a in aliases:
        if a.lower() in lower_map:
            return lower_map[a.lower()]
    return None


def _detect_useful_columns(all_columns: List[str]):
    """Return (text_col, label_col) detected from column names."""
    text_col = LOCAL_TEXT_COLUMN or _pick_first_present(all_columns, TEXT_ALIASES)
    label_col = LOCAL_LABEL_COLUMN or _pick_first_present(all_columns, LABEL_ALIASES)
    return text_col, label_col


# ── Helpers: file discovery ─────────────────────────────────────────────

def _collect_csvs(split_dir: Path, task_type: str, use_binary_multi: bool = False) -> List[Path]:
    """
    Collect CSV files from split directory.
    Handles multiple folder naming patterns:
    - Pattern 1: {task_type}/ (e.g., binary/, ternary/)
    - Pattern 2: {task_type}_{split}/ (e.g., binary_train/, binary_dev/, binary_test/)
    - Pattern 3: {task_type}_(multi|single)_train/ for binary (e.g., binary_multi_train/)
    """
    task_subdir = "binary" if task_type == "binary" else "ternary"
    split_name = split_dir.name  # e.g., "train", "dev", "test"

    # Build candidate folder names
    candidates = []

    # Pattern 1: Simple task type folder
    candidates.append(split_dir / task_subdir)

    # Pattern 2: task_type_split naming (e.g., binary_train, binary_dev)
    candidates.append(split_dir / f"{task_subdir}_{split_name}")

    # Pattern 3: For binary during training, include multi/single variants
    if task_type == "binary":
        if split_name == "train":
            if use_binary_multi:
                candidates.append(split_dir / "binary_multi_train")
            candidates.append(split_dir / "binary_single_train")
        else:
            # For dev/test, try dev/test-specific naming
            candidates.append(split_dir / f"binary_multi_{split_name}")
            candidates.append(split_dir / f"binary_single_{split_name}")

    # For ternary, also try multi/single patterns if they exist
    if task_type == "ternary" and split_name == "train":
        candidates.append(split_dir / "ternary_multi_train")
        candidates.append(split_dir / "ternary_single_train")

    csv_paths: List[Path] = []
    for folder in candidates:
        if folder.exists():
            csv_paths.extend(sorted(folder.rglob("*.csv")))

    # Also check for CSVs directly in the split directory
    if not csv_paths:
        csv_paths = sorted(split_dir.rglob("*.csv"))

    assert csv_paths, f"No CSV files found for split={split_dir.name}, task={task_type}. Tried: {[str(c) for c in candidates]}"
    return csv_paths


def _find_dataset_root(base_dir: Path) -> Path:
    """Walk the extraction directory to find the root that contains train/dev/test splits."""
    # Check if the base_dir itself has the expected structure
    if (base_dir / "train").exists():
        return base_dir
    # Sometimes extraction creates a nested directory
    for child in sorted(base_dir.iterdir()):
        if child.is_dir() and (child / "train").exists():
            return child
        # Go one more level deep
        if child.is_dir():
            for grandchild in sorted(child.iterdir()):
                if grandchild.is_dir() and (grandchild / "train").exists():
                    return grandchild
    raise FileNotFoundError(f"Could not locate train/ split under {base_dir}")


def _extract_all_zips(zip_dir: Path, out_dir: Path):
    """Extract all ZIP files from zip_dir into out_dir, then delete the ZIPs to free disk space."""
    os.makedirs(out_dir, exist_ok=True)
    for zf in sorted(zip_dir.glob("*.zip")):
        print(f"Extracting: {zf.name}")
        with zipfile.ZipFile(zf, "r") as z:
            z.extractall(out_dir)
        print(f"Extracted: {zf.name}")
        zf.unlink()
        print(f"Deleted zip: {zf.name}")


# ── RAM-efficient CSV loader ───────────────────────────────────────────

def _load_csvs_to_dataset(csv_paths: List[Path], max_rows: Optional[int] = None) -> Dataset:
    """
    Stream CSVs in chunks, keeping only the text + label columns.
    Drops rows where text exceeds MAX_TEXT_CHARS.
    Stops early once max_rows is reached.
    """
    # Peek at the first file to detect columns
    peek = pd.read_csv(csv_paths[0], nrows=5)
    text_col, label_col = _detect_useful_columns(list(peek.columns))
    keep_cols = [c for c in [text_col, label_col] if c is not None]
    if not keep_cols:
        # Fallback: keep all columns (small files)
        keep_cols = None
    print(f"  Keeping columns: {keep_cols or 'ALL'}")

    collected_rows = 0
    frames: List[pd.DataFrame] = []

    for p in csv_paths:
        if max_rows and collected_rows >= max_rows:
            break
        try:
            for chunk in pd.read_csv(p, chunksize=CSV_CHUNK_SIZE, usecols=keep_cols):
                # Drop rows with excessively long text to save RAM
                if text_col and text_col in chunk.columns:
                    chunk = chunk[chunk[text_col].astype(str).str.len() <= MAX_TEXT_CHARS]
                # Drop rows with missing values
                chunk = chunk.dropna()
                if len(chunk) == 0:
                    continue
                if max_rows and collected_rows + len(chunk) > max_rows:
                    chunk = chunk.iloc[: max_rows - collected_rows]
                frames.append(chunk)
                collected_rows += len(chunk)
                if max_rows and collected_rows >= max_rows:
                    break
        except Exception as e:
            print(f"  Skipping {p.name}: {e}")

    assert frames, f"No valid CSV data from: {[str(p) for p in csv_paths]}"
    combined = pd.concat(frames, ignore_index=True)
    del frames
    gc.collect()
    print(f"  Total rows loaded: {len(combined)}")

    ds = Dataset.from_pandas(combined)
    del combined
    gc.collect()
    return ds


# ── Main data loader ──────────────────────────────────────────────────

def load_local_data():
    """
    Load local NyayaAnumana CSV data based on the detected runtime environment.
    Returns (train_dataset, eval_dataset) or (train_dataset, None) if no dev split is available.
    """
    data_root = None

    if runtime_env == "colab":
        out_dir = Path(LOCAL_EXTRACT_DIR)
        zip_dir = Path(GDRIVE_ZIP_DIR)
        if out_dir.exists() and any(out_dir.iterdir()):
            print(f"Using previously extracted data at {out_dir}")
        elif zip_dir.exists():
            _extract_all_zips(zip_dir, out_dir)
        else:
            print(f"WARNING: No data found at {zip_dir} or {out_dir}")
            return None, None
        data_root = _find_dataset_root(out_dir)

    elif runtime_env == "kaggle":
        # Check Kaggle working directory first (from GDrive download), then input dir
        for candidate in [Path(KAGGLE_WORKING_DIR), Path(KAGGLE_INPUT_DIR)]:
            if candidate.exists() and any(candidate.iterdir()):
                try:
                    data_root = _find_dataset_root(candidate)
                    break
                except FileNotFoundError:
                    continue
        if data_root is None:
            print("WARNING: No local data found on Kaggle. Check KAGGLE_INPUT_DIR or enable DOWNLOAD_FROM_GDRIVE.")
            return None, None

    else:  # local
        # Look for data in the current working directory or common locations
        for candidate in [Path(LOCAL_EXTRACT_DIR), Path("./nyayaanumana_data"), Path("./data")]:
            if candidate.exists():
                try:
                    data_root = _find_dataset_root(candidate)
                    break
                except FileNotFoundError:
                    continue
        if data_root is None:
            print("WARNING: No local dataset directory found. Set USE_LOCAL_NYAYAANUMANA=False to use HuggingFace Hub.")
            return None, None

    print(f"Dataset root: {data_root}")

    # Load train split (capped at MAX_TRAIN_ROWS)
    train_dir = data_root / "train"
    assert train_dir.exists(), f"Train directory not found: {train_dir}"
    train_csvs = _collect_csvs(train_dir, TASK_TYPE, USE_BINARY_MULTI_TRAIN)
    print(f"Found {len(train_csvs)} train CSV(s) — loading up to {MAX_TRAIN_ROWS} rows")
    train_ds = _load_csvs_to_dataset(train_csvs, max_rows=MAX_TRAIN_ROWS)

    # Load dev/eval split (capped at MAX_EVAL_ROWS)
    eval_ds = None
    dev_dir = data_root / "dev"
    if dev_dir.exists():
        try:
            dev_csvs = _collect_csvs(dev_dir, TASK_TYPE, False)
            print(f"Found {len(dev_csvs)} dev CSV(s) — loading up to {MAX_EVAL_ROWS} rows")
            eval_ds = _load_csvs_to_dataset(dev_csvs, max_rows=MAX_EVAL_ROWS)
        except (AssertionError, Exception) as e:
            print(f"Dev split not usable: {e}")
    else:
        print("No dev directory found; eval split will be created from train split.")

    print(f"Train rows: {len(train_ds)}, Eval rows: {len(eval_ds) if eval_ds else 'None (will split from train)'}")
    return train_ds, eval_ds


print("Data loading functions defined.")

Data loading functions defined.

In [ ]:
def download_and_extract_gdrive_data():
    """Download ZIPs from Google Drive and extract them."""
    urls_to_download = []

    # Build URL list from file IDs and/or direct URLs
    for fid in GDRIVE_FILE_IDS:
        urls_to_download.append(f"https://drive.google.com/uc?id={fid}")
    urls_to_download.extend(GDRIVE_FILE_URLS)

    if not urls_to_download:
        print("GDRIVE download skipped: no file IDs or URLs provided.")
        return

    os.makedirs(GDRIVE_DOWNLOAD_OUTPUT_DIR, exist_ok=True)
    os.makedirs(LOCAL_EXTRACT_DIR, exist_ok=True)

    import gdown

    for url in urls_to_download:
        # Derive a filename from the URL
        try:
            file_part = url.split('/')[-2] if '/d/' in url else url.split('=')[-1]
        except Exception:
            file_part = "download"
        output_zip = os.path.join(GDRIVE_DOWNLOAD_OUTPUT_DIR, file_part + ".zip")
        print(f"Downloading {url} -> {output_zip}")
        try:
            gdown.download(url, output_zip, quiet=False, fuzzy=True)
            if os.path.exists(output_zip) and zipfile.is_zipfile(output_zip):
                with zipfile.ZipFile(output_zip, 'r') as zip_ref:
                    zip_ref.extractall(LOCAL_EXTRACT_DIR)
                print(f"Extracted {output_zip} to {LOCAL_EXTRACT_DIR}")
                # Free disk space by deleting the ZIP after extraction
                os.remove(output_zip)
                print(f"Deleted zip: {output_zip}")
            else:
                print(f"WARNING: {output_zip} is not a valid ZIP file.")
        except Exception as e:
            print(f"Error processing {url}: {e}")


# Download from GDrive if enabled
if DOWNLOAD_FROM_GDRIVE:
    download_and_extract_gdrive_data()

# # Load the dataset
# if USE_LOCAL_NYAYAANUMANA:
#     raw_train_ds, raw_eval_ds = load_local_data()
#     if raw_train_ds is None:
#         print("ERROR: Local data loading failed. Set USE_LOCAL_NYAYAANUMANA=False to try HuggingFace Hub.")
#     else:
#         print(f"Loaded local data: train={len(raw_train_ds)}, eval={len(raw_eval_ds) if raw_eval_ds else 'None'}")
# else:
#     # Load from HuggingFace Hub
#     print(f"Loading dataset from HuggingFace Hub: {DATASET_NAME}")
#     try:
#         hf_ds = load_dataset(DATASET_NAME, split=DATASET_SPLIT)
#     except Exception as e:
#         print(f"Primary dataset failed ({e}), trying fallback: {DATASET_FALLBACK_NAME}")
#         hf_ds = load_dataset(DATASET_FALLBACK_NAME, split=DATASET_SPLIT)
#     raw_train_ds = hf_ds
#     raw_eval_ds = None
#     print(f"Loaded HuggingFace dataset: {len(raw_train_ds)} rows")
#     print(f"Columns: {raw_train_ds.column_names}")

Downloading https://drive.google.com/file/d/1orjPv04pb-t_iQZQWbZ8eqhbgU5lcEl2/view?usp=sharing -> ./nyayaanumana_gdrive_zips/1orjPv04pb-t_iQZQWbZ8eqhbgU5lcEl2.zip

Downloading...
From (original): https://drive.google.com/uc?id=1orjPv04pb-t_iQZQWbZ8eqhbgU5lcEl2
From (redirected): https://drive.google.com/uc?id=1orjPv04pb-t_iQZQWbZ8eqhbgU5lcEl2&confirm=t&uuid=b74e3755-ea76-4cad-a2ff-062fc0e41cb9
To: /content/nyayaanumana_gdrive_zips/1orjPv04pb-t_iQZQWbZ8eqhbgU5lcEl2.zip
100%|██████████| 1.13G/1.13G [00:13<00:00, 80.9MB/s]

Extracted ./nyayaanumana_gdrive_zips/1orjPv04pb-t_iQZQWbZ8eqhbgU5lcEl2.zip to /content/nyayaanumana_data
Deleted zip: ./nyayaanumana_gdrive_zips/1orjPv04pb-t_iQZQWbZ8eqhbgU5lcEl2.zip
Downloading https://drive.google.com/file/d/15CEkIWUycA8zomYXyMobKWfWgEhXSzrm/view?usp=sharing -> ./nyayaanumana_gdrive_zips/15CEkIWUycA8zomYXyMobKWfWgEhXSzrm.zip

Downloading...
From (original): https://drive.google.com/uc?id=15CEkIWUycA8zomYXyMobKWfWgEhXSzrm
From (redirected): https://drive.google.com/uc?id=15CEkIWUycA8zomYXyMobKWfWgEhXSzrm&confirm=t&uuid=b2e82bc6-6220-4682-ba0d-b3c35acfcaa3
To: /content/nyayaanumana_gdrive_zips/15CEkIWUycA8zomYXyMobKWfWgEhXSzrm.zip
100%|██████████| 2.97G/2.97G [00:41<00:00, 71.7MB/s]

Extracted ./nyayaanumana_gdrive_zips/15CEkIWUycA8zomYXyMobKWfWgEhXSzrm.zip to /content/nyayaanumana_data
Deleted zip: ./nyayaanumana_gdrive_zips/15CEkIWUycA8zomYXyMobKWfWgEhXSzrm.zip
Downloading https://drive.google.com/file/d/1BW1L248iV6NBSJVWdCk5vAeKVHumWcmi/view?usp=sharing -> ./nyayaanumana_gdrive_zips/1BW1L248iV6NBSJVWdCk5vAeKVHumWcmi.zip

Downloading...
From (original): https://drive.google.com/uc?id=1BW1L248iV6NBSJVWdCk5vAeKVHumWcmi
From (redirected): https://drive.google.com/uc?id=1BW1L248iV6NBSJVWdCk5vAeKVHumWcmi&confirm=t&uuid=cbb8c382-4025-4e6a-91da-7e60e611a9b2
To: /content/nyayaanumana_gdrive_zips/1BW1L248iV6NBSJVWdCk5vAeKVHumWcmi.zip
100%|██████████| 14.2G/14.2G [04:06<00:00, 57.5MB/s]

Extracted ./nyayaanumana_gdrive_zips/1BW1L248iV6NBSJVWdCk5vAeKVHumWcmi.zip to /content/nyayaanumana_data
Deleted zip: ./nyayaanumana_gdrive_zips/1BW1L248iV6NBSJVWdCk5vAeKVHumWcmi.zip
Using previously extracted data at /content/nyayaanumana_data
Dataset root: /content/nyayaanumana_data
Found 1 train CSV(s) — loading up to 3000 rows
  Keeping columns: ['text', 'label']

NameError: name 'gc' is not defined

In [ ]:
MAX_TRAIN_ROWS = 1000   # Max training rows to keep (set None for unlimited)
MAX_EVAL_ROWS  = 300    # Max eval rows to keep
CSV_CHUNK_SIZE = 1000   # Rows per pandas chunk while reading CSVs
MAX_TEXT_CHARS = 10000   # Drop rows whose text column exceeds this length

In [ ]:
import gc
if USE_LOCAL_NYAYAANUMANA:
    raw_train_ds, raw_eval_ds = load_local_data()
    if raw_train_ds is None:
        print("ERROR: Local data loading failed. Set USE_LOCAL_NYAYAANUMANA=False to try HuggingFace Hub.")
    else:
        print(f"Loaded local data: train={len(raw_train_ds)}, eval={len(raw_eval_ds) if raw_eval_ds else 'None'}")
else:
    # Load from HuggingFace Hub
    print(f"Loading dataset from HuggingFace Hub: {DATASET_NAME}")
    try:
        hf_ds = load_dataset(DATASET_NAME, split=DATASET_SPLIT)
    except Exception as e:
        print(f"Primary dataset failed ({e}), trying fallback: {DATASET_FALLBACK_NAME}")
        hf_ds = load_dataset(DATASET_FALLBACK_NAME, split=DATASET_SPLIT)
    raw_train_ds = hf_ds
    raw_eval_ds = None
    print(f"Loaded HuggingFace dataset: {len(raw_train_ds)} rows")
    print(f"Columns: {raw_train_ds.column_names}")

Using previously extracted data at /content/nyayaanumana_data
Dataset root: /content/nyayaanumana_data
Found 1 train CSV(s) — loading up to 1000 rows
  Keeping columns: ['text', 'label']
  Total rows loaded: 1000
Found 1 dev CSV(s) — loading up to 300 rows
  Keeping columns: ['text', 'label']
  Total rows loaded: 300
Train rows: 1000, Eval rows: 300
Loaded local data: train=1000, eval=300

## 5. Prepare Preference Pairs for DPO (`prompt`, `chosen`, `rejected`)

In [ ]:
def _build_prompt_from_case(text: str) -> str:
    return (
        "You are a legal AI assistant. Read the following case description and provide the correct class.\n\n"
        f"Case description:\n{text}\n\n"
        "Return one of these labels: Rejected, Accepted, Multi-label."
    )


def _label_to_response(label_value: int) -> str:
    if label_value == 0:
        return "Classification: Rejected\nRationale: The case outcome indicates rejection."
    if label_value == 1:
        return "Classification: Accepted\nRationale: The case outcome indicates acceptance."
    return "Classification: Multi-label\nRationale: The case contains a mix of accepted and rejected judgments."


def _build_dpo_from_classification(ds: Dataset, max_rows: Optional[int] = None) -> Dataset:
    """Convert classification rows to DPO triples, capped at max_rows."""
    columns = ds.column_names
    text_col = LOCAL_TEXT_COLUMN or _pick_first_present(columns, TEXT_ALIASES)
    label_col = LOCAL_LABEL_COLUMN or _pick_first_present(columns, LABEL_ALIASES)

    assert text_col is not None, f"Could not infer text column from: {columns}"
    assert label_col is not None, f"Could not infer label column from: {columns}"

    allowed_labels = [0, 1] if TASK_TYPE == "binary" else [0, 1, 2]
    rows = []

    for ex in ds:
        if max_rows and len(rows) >= max_rows:
            break

        text = str(ex.get(text_col, "") or "").strip()
        raw_label = ex.get(label_col, None)
        if text == "" or raw_label is None:
            continue
        # Skip excessively long texts (already filtered at CSV level, but double-check)
        if len(text) > MAX_TEXT_CHARS:
            continue

        try:
            label_int = int(raw_label)
        except Exception:
            continue

        if TASK_TYPE == "binary" and label_int == 2 and MERGE_MULTILABEL_TO_ACCEPTED:
            label_int = 1

        if label_int not in allowed_labels:
            continue

        prompt = _build_prompt_from_case(text)
        chosen = _label_to_response(label_int)

        # Deterministic negative class for reproducibility.
        rejected_label = next(x for x in allowed_labels if x != label_int)
        rejected = _label_to_response(rejected_label)

        if prompt and chosen and rejected and chosen != rejected:
            rows.append({"prompt": prompt, "chosen": chosen, "rejected": rejected})

    assert rows, "No valid DPO rows were created from classification data"
    return Dataset.from_list(rows)


def _build_dpo_from_preference(ds: Dataset, max_rows: Optional[int] = None) -> Dataset:
    """Build DPO triples from a preference-style dataset, capped at max_rows."""
    columns = ds.column_names
    prompt_col = _pick_first_present(columns, ["prompt", "question", "query", "instruction"])
    chosen_col = _pick_first_present(columns, ["chosen", "preferred", "answer", "response", "output"])
    rejected_col = _pick_first_present(columns, ["rejected", "dispreferred", "bad_answer", "negative"])
    input_col = _pick_first_present(columns, ["input", "context", "details"])

    assert prompt_col is not None, "Could not infer a prompt-like column"
    assert chosen_col is not None, "Could not infer a chosen/output-like column"

    def build_prompt(example: Dict) -> str:
        base = str(example.get(prompt_col, "") or "").strip()
        extra = str(example.get(input_col, "") or "").strip() if input_col else ""
        return f"{base}\n\nAdditional context:\n{extra}" if extra and base else (extra or base)

    records = []
    # Avoid materializing all_outputs for the whole dataset — only compute rejects on the fly
    n = len(ds)

    for i, ex in enumerate(ds):
        if max_rows and len(records) >= max_rows:
            break

        prompt = build_prompt(ex)
        chosen = str(ex.get(chosen_col, "") or "").strip()
        rejected = str(ex.get(rejected_col, "") or "").strip() if rejected_col else ""
        if not rejected:
            # Use the next row's chosen as a synthetic reject
            next_ex = ds[(i + 1) % n]
            rejected = str(next_ex.get(chosen_col, "") or "").strip()
        if prompt and chosen and rejected and chosen != rejected:
            records.append({"prompt": prompt, "chosen": chosen, "rejected": rejected})

    assert records, "No valid DPO records were created"
    return Dataset.from_list(records)


# Build DPO preference pairs from the loaded raw data
if USE_LOCAL_NYAYAANUMANA:
    assert raw_train_ds is not None, "raw_train_ds is None. Local data loading may have failed."
    dpo_train_ds = _build_dpo_from_classification(raw_train_ds, max_rows=MAX_TRAIN_ROWS)
    if raw_eval_ds is not None:
        dpo_eval_ds = _build_dpo_from_classification(raw_eval_ds, max_rows=MAX_EVAL_ROWS)
    else:
        split_tmp = dpo_train_ds.train_test_split(test_size=0.05, seed=SEED)
        dpo_train_ds, dpo_eval_ds = split_tmp["train"], split_tmp["test"]
        del split_tmp
else:
    dpo_full_ds = _build_dpo_from_preference(raw_train_ds, max_rows=MAX_TRAIN_ROWS)
    split_tmp = dpo_full_ds.train_test_split(test_size=0.05, seed=SEED)
    dpo_train_ds, dpo_eval_ds = split_tmp["train"], split_tmp["test"]
    del dpo_full_ds, split_tmp

# Free the raw datasets — we only need the DPO triples from here on
del raw_train_ds
if 'raw_eval_ds' in dir():
    del raw_eval_ds
gc.collect()

print(f"DPO train records: {len(dpo_train_ds)}")
print(f"DPO eval records: {len(dpo_eval_ds)}")
print("Sample DPO record:")
print(dpo_train_ds[0])

DPO train records: 1000
DPO eval records: 300
Sample DPO record:
{'prompt': 'You are a legal AI assistant. Read the following case description and provide the correct class.\n\nCase description:\nFirst Bail Application No.288 of 2015 Order on the bail application of accused Criminal Side Deewan Singh Rawat, S o Sovan Singh Rawat, R o Village - Chamiyadi, Post Jamnikhal, Police Station - Hindolakhal, District - Tehri Garhwal.Applicant Versus State of Respondent Honble Sudhanshu Dhulia, J.(Oral) Heard Mr. Amar Shukla, Advocate for the applicant and Mr. B.M.Pingal, learned Brief Holder for the State of The applicant is in jail having been implicated in Case Crime No.01 of 2015, which has been under Sections of Wild Life (Protection) Act, 1972, at Police Station Devprayag, District Tehri Garhwal.As per the case of the prosecution, the applicant was found sitting in the car from where recovery of bones of animals was made.Learned counsel for the applicant contends that Virendra Dutt Semwal having similar allegations against him has already been granted bail by this Court vide order dated 14.05.2015 passed in BA1 No.361 of 2015.Considering the overall which is presently before this Court, particularly keeping in view the ground of parity, the applicant has been able to make out a case for bail.\n\nReturn one of these labels: Rejected, Accepted, Multi-label.', 'chosen': 'Classification: Accepted\nRationale: The case outcome indicates acceptance.', 'rejected': 'Classification: Rejected\nRationale: The case outcome indicates rejection.'}

## 6. Tokenize and Apply Chat Template

In [ ]:
def to_chat_prompt_text(prompt: str) -> str:
    messages = [{"role": "user", "content": prompt}]
    return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)


def _filter_and_format(ds: Dataset) -> Dataset:
    formatted_records = []
    for ex in ds:
        chat_prompt = to_chat_prompt_text(ex["prompt"])
        prompt_len = len(tokenizer(chat_prompt, add_special_tokens=False)["input_ids"])
        chosen_len = len(tokenizer(ex["chosen"], add_special_tokens=False)["input_ids"])
        rejected_len = len(tokenizer(ex["rejected"], add_special_tokens=False)["input_ids"])

        if prompt_len < MAX_SEQ_LENGTH and chosen_len > 0 and rejected_len > 0:
            formatted_records.append(
                {
                    "prompt": chat_prompt,
                    "chosen": ex["chosen"],
                    "rejected": ex["rejected"],
                }
            )

    assert formatted_records, "No rows left after formatting and filtering"
    return Dataset.from_list(formatted_records)


train_ds = _filter_and_format(dpo_train_ds)
eval_ds = _filter_and_format(dpo_eval_ds)

# Free DPO intermediates
del dpo_train_ds, dpo_eval_ds
gc.collect()

print(f"Train size: {len(train_ds)}")
print(f"Eval size: {len(eval_ds)}")
print("Formatted sample:")
print(train_ds[0])

Train size: 721
Eval size: 219
Formatted sample:
{'prompt': '<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nYou are a legal AI assistant. Read the following case description and provide the correct class.\n\nCase description:\nFirst Bail Application No.288 of 2015 Order on the bail application of accused Criminal Side Deewan Singh Rawat, S o Sovan Singh Rawat, R o Village - Chamiyadi, Post Jamnikhal, Police Station - Hindolakhal, District - Tehri Garhwal.Applicant Versus State of Respondent Honble Sudhanshu Dhulia, J.(Oral) Heard Mr. Amar Shukla, Advocate for the applicant and Mr. B.M.Pingal, learned Brief Holder for the State of The applicant is in jail having been implicated in Case Crime No.01 of 2015, which has been under Sections of Wild Life (Protection) Act, 1972, at Police Station Devprayag, District Tehri Garhwal.As per the case of the prosecution, the applicant was found sitting in the car from where recovery of bones of animals was made.Learned counsel for the applicant contends that Virendra Dutt Semwal having similar allegations against him has already been granted bail by this Court vide order dated 14.05.2015 passed in BA1 No.361 of 2015.Considering the overall which is presently before this Court, particularly keeping in view the ground of parity, the applicant has been able to make out a case for bail.\n\nReturn one of these labels: Rejected, Accepted, Multi-label.<|im_end|>\n<|im_start|>assistant\n', 'chosen': 'Classification: Accepted\nRationale: The case outcome indicates acceptance.', 'rejected': 'Classification: Rejected\nRationale: The case outcome indicates rejection.'}

## 7. Configure LoRA and DPO Training Arguments

In [ ]:
from trl import DPOConfig, DPOTrainer

BETA = 0.1
PER_DEVICE_BATCH_SIZE = 2
GRAD_ACCUM_STEPS = 2
LEARNING_RATE = 5e-6
MAX_STEPS = 100
LOGGING_STEPS = 10
SAVE_STEPS = 25
EVAL_STEPS = 100

training_args = DPOConfig(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=PER_DEVICE_BATCH_SIZE,
    per_device_eval_batch_size=PER_DEVICE_BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUM_STEPS,
    learning_rate=LEARNING_RATE,
    max_steps=MAX_STEPS,
    warmup_ratio=0.05,
    lr_scheduler_type="cosine",
    logging_steps=LOGGING_STEPS,
    eval_strategy="steps",
    eval_steps=EVAL_STEPS,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    save_total_limit=2,
    bf16=USE_BF16,
    fp16=False,
    report_to="none",
    max_prompt_length=512,
    max_length=1024,
    beta=BETA,
    remove_unused_columns=False,
    seed=SEED,
    dataloader_pin_memory=False,   # Save RAM — disable pinned memory
    dataloader_num_workers=0,
    # resume_from_checkpoint=True,  # optional safety
)


if not hasattr(model, 'warnings_issued'):
    model.warnings_issued = {}

trainer = DPOTrainer(
    model=model,
    ref_model=None,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    processing_class=tokenizer,
)

print("DPO trainer initialized")

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Extracting prompt in train dataset:   0%|          | 0/721 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/721 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/721 [00:00<?, ? examples/s]

Extracting prompt in eval dataset:   0%|          | 0/219 [00:00<?, ? examples/s]

Applying chat template to eval dataset:   0%|          | 0/219 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/219 [00:00<?, ? examples/s]

DPO trainer initialized

## 8. Run DPO Training Loop

In [ ]:
# ❌ REMOVE this from here
# FastLanguageModel.for_inference(model)

def generate_answer(user_prompt: str, max_new_tokens: int = 256) -> str:
    prompt_text = tokenizer.apply_chat_template(
        [{"role": "user", "content": user_prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(prompt_text, return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            pad_token_id=tokenizer.eos_token_id,
        )
    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return decoded[len(prompt_text):].strip() if decoded.startswith(prompt_text) else decoded

sample_prompts = [
    "Explain the difference between bailable and non-bailable offences under Indian law.",
    "Draft a short legal notice for non-payment of rent under a commercial lease.",
]

# ✅ OPTIONAL: test BEFORE training (keep model in training mode)
print("=== Before Resume (sanity sample) ===")
for p in sample_prompts:
    print("\nPrompt:", p)
    print("Response:", generate_answer(p, max_new_tokens=180))


# ✅ RESUME TRAINING
train_result = trainer.train()

print(train_result)


# ✅ Save final model
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)


# ✅ NOW switch to inference mode
FastLanguageModel.for_inference(model)

print("\n=== After Training ===")
for p in sample_prompts:
    print("\nPrompt:", p)
    print("Response:", generate_answer(p, max_new_tokens=180))

=== Before Resume (sanity sample) ===

Prompt: Explain the difference between bailable and non-bailable offences under Indian law.

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response: system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.
user
Explain the difference between bailable and non-bailable offences under Indian law.
assistant
Under the Indian legal system, certain offenses can be categorized as "bailable" and others as "non-bailable." This classification is based on the severity of the offense and its impact on public interest. The distinction is important because it determines whether an accused person can be released on bail or not. Here's a detailed explanation:

### Bailable Offences

Bailable offences are those for which the accused can be released on bail. If a person commits a bailable offence, he or she has the right to apply for bail under the Indian Penal Code (IPC) or any other applicable laws. The main criterion for being a bailable offence is that it does not involve serious harm to society or individuals.

**Key Characteristics:**
1. **Minority in Nature:** These offenses generally relate to minor crimes or infractions.
2. **Public Interest:** They do not pose a significant threat to

Prompt: Draft a short legal notice for non-payment of rent under a commercial lease.

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

Response: system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.
user
Draft a short legal notice for non-payment of rent under a commercial lease.
assistant
### Legal Notice for Non-Payment of Rent

[Your Company’s Letterhead]

[Date]

[Landlord’s Address]

[Landlord’s Contact Information]

[Property Address]

[Copies Sent to: Tenant’s Name, Tenant’s Address, Tenant’s Email/Phone Number]

[Dear [Tenant’s Name],

We hope this letter finds you well.

---

**Subject:** Legal Notice for Non-Payment of Rent

Dear [Tenant’s Name],

**Introduction:**

This letter is being sent to remind you that your rental payments for the property located at [Property Address] have not been received as per our agreement. As detailed in the commercial lease agreement between us, the rent is due on the first day of each month and must be paid within 10 days thereafter.

**Details of Non-Payment:**

As of today, the rent for the month of [Month Year]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 721 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 2 x 1) = 4
 "-____-"     Trainable parameters = 29,933,568 of 3,115,872,256 (0.96% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!

Unsloth: Will smartly offload gradients to save VRAM!

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:254: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

TrainOutput(global_step=100, training_loss=0.680384521484375, metrics={'train_runtime': 1100.9247, 'train_samples_per_second': 0.363, 'train_steps_per_second': 0.091, 'total_flos': 0.0, 'train_loss': 0.680384521484375, 'epoch': 0.554016620498615})

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== After Training ===

Prompt: Explain the difference between bailable and non-bailable offences under Indian law.

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response: system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.
user
Explain the difference between bailable and non-bailable offences under Indian law.
assistant
Under the Indian Penal Code (IPC) and the Indian Evidence Act, there is a distinction made regarding the ability of an accused person to be released on bail. This distinction is based on the severity or nature of the offence committed.

### Bailable Offences

An offence is considered "bailable" if it falls within certain categories as defined in Section 314(1)(a) of the IPC. An accused person who is charged with a bailable offence can generally be released on bail. The conditions for release on bail include:

1. **Presumption of Innocence**: There is no presumption that the accused is guilty.
2. **Probable Presence**: There is no reasonable likelihood that the accused will flee or obstruct justice.
3. **Ease of Production**: The accused can be produced before the court without delay.
4. **Sufficient Security**: The accused provides sufficient security (

Prompt: Draft a short legal notice for non-payment of rent under a commercial lease.
Response: system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.
user
Draft a short legal notice for non-payment of rent under a commercial lease.
assistant
Subject: Urgent Notice of Non-Payment of Rent Under Commercial Lease Agreement

Dear [Landlord's Name],

I hope this letter finds you well.

We write to formally notify you that you have not paid the rent in accordance with the terms and conditions stipulated in the Commercial Lease Agreement dated [Insert Date] (the "Agreement").

Pursuant to Section 3.2 of the Agreement, rent is due on the first day of each calendar month and must be paid in full no later than the fifth day of the following month. As of today, you are still in arrears for the rent for the period ending [Insert Last Month]. The total amount owed is [Insert Amount], including interest at a rate of [Insert Rate]% per month if unpaid within ten days of the due date.

Failure to pay the overdue rent will result in the termination of the lease agreement,

## 9. Evaluate with Sample Legal Prompts

In [ ]:
print("=== After DPO (sanity sample) ===")
for p in sample_prompts:
    print("\nPrompt:", p)
    print("Response:", generate_answer(p, max_new_tokens=180))

# Lightweight proxy metrics for quick inspection.
avg_prompt_len = np.mean([len(x["prompt"]) for x in eval_ds.select(range(min(200, len(eval_ds))))])
avg_chosen_len = np.mean([len(x["chosen"]) for x in eval_ds.select(range(min(200, len(eval_ds))))])
print(f"Eval proxy metric - avg prompt chars: {avg_prompt_len:.2f}")
print(f"Eval proxy metric - avg chosen chars: {avg_chosen_len:.2f}")

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== After DPO (sanity sample) ===

Prompt: Explain the difference between bailable and non-bailable offences under Indian law.

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response: system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.
user
Explain the difference between bailable and non-bailable offences under Indian law.
assistant
Under Indian law, the classification of offences as "bailable" or "non-bailable" is based on the severity of the offense, the discretion of the judicial officer, and certain other factors. Here's an explanation of the key differences:

### Bailable Offences:
Bailable offences are those offenses where the accused can apply for release from custody before the trial begins. This right to bail is generally available unless there are specific reasons to deny it.

**Key Characteristics:**
1. **Mere Commitment for Remand:** Generally, the accused can be committed only to be present in court (remanded) and not kept in custody.
2. **Right to Bail:** The accused has the right to apply for bail even before the charges are finalized.
3. **Reasons for Denial:** The court may refuse to grant bail if it is satisfied that the accused would abscond or

Prompt: Draft a short legal notice for non-payment of rent under a commercial lease.
Response: system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.
user
Draft a short legal notice for non-payment of rent under a commercial lease.
assistant
### Legal Notice for Non-Payment of Rent

**[Your Company Name]**
**[Your Company Address]**
**[City, State, Zip Code]**

**[Date]**

**[Tenant’s Name]**
**[Tenant's Address]**
**[City, State, Zip Code]**

Dear [Tenant’s Name],

RE: Non-Payment of Rent

We write to formally inform you that your rental payment for the month of [Month and Year] has not yet been received. According to our records, the amount due is [Total Amount Due].

As per the terms of the Commercial Lease Agreement (No. [Lease Agreement Number]), it is clearly stated that tenants are required to make timely rent payments in accordance with the schedule provided in the lease.

Failure to pay the aforementioned rent within [X] days from the date of this notice will result in the following actions
Eval proxy metric - avg prompt chars: 3536.27
Eval proxy metric - avg chosen chars: 73.68

## 10. Save, Merge, and Export the Fine-Tuned Model

Adapter and tokenizer are already saved to OUTPUT_DIR.

Optional merge for standalone inference:

```python
merged_dir = f"{OUTPUT_DIR}/merged_16bit"
model.save_pretrained_merged(merged_dir, tokenizer, save_method="merged_16bit")
print("Merged model saved to", merged_dir)
```

Optional Hub push (fill your repo id):

```python
# from huggingface_hub import login
# login()
# model.push_to_hub_merged("your-username/your-legal-dpo-model", tokenizer, save_method="merged_16bit")
```

DPO objective reminder: the training balances preference strength using $\beta$, where larger $\beta$ puts more emphasis on matching chosen-over-rejected preferences.

In [ ]:
merged_dir = f"{OUTPUT_DIR}/merged_16bit"
model.save_pretrained_merged(merged_dir, tokenizer, save_method="merged_16bit")
print("Merged model saved to", merged_dir)

config.json:   0%|          | 0.00/757 [00:00<?, ?B/s]

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Checking cache directory for required files...
Cache check failed: model-00001-of-00002.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/3.97G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files:  50%|█████     | 1/2 [01:18<01:18, 78.31s/it]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 2/2 [01:41<00:00, 50.73s/it]

Note: tokenizer.model not found (this is OK for non-SentencePiece models)

Unsloth: Merging weights into 16bit:   0%|          | 0/2 [00:00<?, ?it/s]
Unsloth: Merging weights into 16bit:  50%|█████     | 1/2 [01:04<01:04, 64.26s/it]
Unsloth: Merging weights into 16bit: 100%|██████████| 2/2 [01:46<00:00, 53.16s/it]

Unsloth: Merge process complete. Saved to `/content/output_dpo_unsloth_legal/merged_16bit`
Merged model saved to ./output_dpo_unsloth_legal/merged_16bit

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import shutil
import os

source_folder = OUTPUT_DIR
destination_folder = "/content/drive/MyDrive/RLDPO/dpo_unsloth_legal_output"

# Ensure the destination directory exists and is empty or non-existent
if os.path.exists(destination_folder):
    print(f"Warning: Destination folder {destination_folder} already exists. Removing it.")
    shutil.rmtree(destination_folder)

print(f"Copying {source_folder} to {destination_folder}...")
shutil.copytree(source_folder, destination_folder)
print("Copy complete!")

Copying ./output_dpo_unsloth_legal to /content/drive/MyDrive/RLDPO/dpo_unsloth_legal_output...
Copy complete!

In [ ]:
from huggingface_hub import login, upload_folder

# (optional) Login with your Hugging Face credentials
login(token="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")

# Push your model files
upload_folder(folder_path="/content/output_dpo_unsloth_legal/merged_16bit", repo_id="highintoxic/nayanRLDPO", repo_type="model")

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...rged_16bit/tokenizer.json: 100%|##########| 11.4MB / 11.4MB

  ...0002-of-00002.safetensors:   0%|          |  601kB / 2.20GB

  ...0001-of-00002.safetensors:   0%|          | 15.9MB / 3.97GB

CommitInfo(commit_url='https://huggingface.co/highintoxic/nayanRLDPO/commit/90d92e66db744b36cc4a2702fa1ea12868485721', commit_message='Upload folder using huggingface_hub', commit_description='', oid='90d92e66db744b36cc4a2702fa1ea12868485721', pr_url=None, repo_url=RepoUrl('https://huggingface.co/highintoxic/nayanRLDPO', endpoint='https://huggingface.co', repo_type='model', repo_id='highintoxic/nayanRLDPO'), pr_revision=None, pr_num=None)

# Inference

In [ ]:
from unsloth import FastLanguageModel
import torch

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=OUTPUT_DIR,   # your saved model
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)

FastLanguageModel.for_inference(model)

In [ ]:
SYSTEM_PROMPT = """
You are an AI legal assistant specialized in Indian law.

Guidelines:
- Answer strictly based on Indian legal system (IPC, CrPC, CPC, Indian Evidence Act, Constitution of India, and relevant statutes).
- Clearly distinguish between bailable and non-bailable offences, civil and criminal matters when relevant.
- Provide structured, precise, and legally accurate explanations.
- Use simple language unless technical detail is required.
- If drafting legal documents (notices, complaints, etc.), follow standard Indian legal formatting.
- Do not provide false or unverifiable legal claims.
- If unsure, say so instead of hallucinating.
- Do not provide illegal advice or encourage unlawful actions.

Style:
- Professional, concise, and formal.
- Prefer bullet points or sections where clarity is needed.
"""
def build_bail_prompt(case_text: str) -> str:
    return f"""
You are acting as a Sessions Court judge in India deciding a bail application.

Case Details:
{case_text}

Instructions:
- Do NOT assume facts not provided
- Analyze step-by-step like a judge
- Balance personal liberty vs societal interest

Step-by-step Analysis:
1. Nature and gravity of offence
2. Criminal antecedents
3. Possibility of absconding
4. Possibility of evidence tampering
5. Stage of investigation

Then provide final answer in this format:

Decision: (Granted / Denied)

Legal Reasoning:
- Point-wise reasoning based on above factors

Final Order:
- Bail granted or denied with justification

If facts are insufficient, say:
"Insufficient information to decide"
"""

# ==============================
# ✅ GENERATION FUNCTION
# ==============================
def generate_bail_decision(case_text: str, max_new_tokens: int = 300):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": build_bail_prompt(case_text)},
    ]

    prompt_text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(prompt_text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,        # 🔥 deterministic (important for law)
            temperature=0.3,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id,
        )

    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return decoded[len(prompt_text):].strip()